default: true
MD013: false  # line-length
MD014: false  # commands-show-output
MD024: false  # no-duplicate-heading/no-duplicate-header
MD033: false  # inline html, terraform-docs
MD049: false # emphasis-style
