formatter: "markdown"

output:
  file: README.md
  mode: inject

recursive:
  enabled: false


sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: false
  read-comments: true
  required: false
  sensitive: true
  type: true
