name: Terraform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  terraform:
    name: terraform CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # or whatever version you use

      - name: Install dependencies
        run: npm ci
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: hashicorp/setup-terraform@v1

      - name: terraform test
        id: test
        run: |
          terraform init && terraform test -junit-xml=junit.xml -verbose

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/junit.xml'
